### ISSUE TITLE
The game clock stops when the notify umpire button is pressed.

### ISSUE THREAD

**Issue by asahani** [wraus/scoreboardWeb#141] opened 2016-03-16 04:25 UTC

**Comment by hayrich** [comment] 2016-03-16 07:23
can't reproduce, can you please provide steps to reproduce

**Comment by david2202** [comment] 2016-03-16 09:31
I'm unable to reproduce as well.  When I press Umpire the clock keeps running and the sound is made.

**Comment by nsanders88** [comment] 2016-03-16 09:40
Hi guys,

Looking at this one like others I recon you may want to get umpire attention by pushing the button but still kept clock run as they may decide to wait till there is a break in play before coming to the scorer, it would be at the umpire discretion. So possibly simpler to separate the umpire button from the auto time stop?

Regards

Nick

Nick Sanders  MAppSc, BAppSc, BTech
Sport Scientist - Performance Analysis Specialist
Victorian Institute of Sport - Australian Paralympic Committee - Shooting Australia

Lakeside Stadium, 33 Aughtie Drive, Albert Park 3206, Victoria, Australia

P: +61 3 9425 0096 M: +61 409 400 280
F: +61 3 9425 0100             E: nick.sanders@vis.org.aumailto:glen.collins@vis.org.au

“SUCCESS IN SPORT AND LIFE”
www.vis.org.auhttp://www.vis.org.au/

On 16 Mar 2016, at 8:31 PM, david2202 <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm unable to reproduce as well. When I press Umpire the clock keeps running and the sound is made.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://github.com/wraus/scoreboardWeb/issues/141#issuecomment-197226731

---

Message protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.
http://www.mailguard.com.au

Report this message as spamhttps://console.mailguard.com.au/ras/1O2At0j930/1J0Xw6mgfnYlFT4DmamYAI/5.654

## 

Message  protected by MailGuard: e-mail anti-virus, anti-spam and content filtering.
http://www.mailguard.com.au

**Comment by david2202** [comment] 2016-03-16 22:37
@nsanders88 agree. I think this is how it is currently working.

**Comment by hayrich** [comment] 2016-03-16 23:04
closing as appears to be correct behaviour

**Closed as completed by hayrich** 2016-03-16 23:04 UTC
Labels: bug
