### ISSUE TITLE
Do not display shot clock digits when a goal is scored and game time is less than 40 seconds

### ISSUE THREAD

**Issue by hayrich** [wraus/scoreboardWeb#176] opened 2016-04-29 03:03 UTC
Previously we had the Shot Clock automatically disappear once the game clock was less that the shot clock, this was changed so that shot clock box remains but the shot clock numbers disappear once the Game clock is less than 40 and the shot clock is reset to 40s.  
The issue is that if a goal is scored at less than 40s then the shot clock resets to 40s and continues to be shown, so the shot clock will then be more than the game clock creating confusion for the players.

**Comment by david2202** [comment] 2016-04-29 22:33
I've re-tested this on the develop branch and I can't reproduce it.  Steps that I am doing:
1. Start the clock running for a new quarter
2. Adjust the clock down to < 1 minute
3. Start the clock
4. Wait for the clock to run down to less than 40 seconds
5. Press "Reset 40"
6. The shot clock disappears and the clock keeps running
7. Press "Score +" for a goal

I get the goal displayed, the clock stopped and the shot clock is still not displayed.  @nsanders88 is the above sequence correct or are you doing something different?

**Comment by hayrich** [comment] 2016-04-30 00:04
Sorry David, I should've added the following video capture Nick sent me earlier of the issue.

[video](https://youtu.be/kEXpHIi2rLU)
1. Start the clock running for a new quarter
2. Adjust the game clock down 30 secs
3. Adjust the shot clock down 20 secs
4. Click start
5. Press Score +
6. The shot clock is reset to 40 and displays as 40 even though the game clock is less than 40
7. This is the issue, the shot clock digits should not appear if greater than game clock.

**Comment by david2202** [comment] 2016-04-30 03:06
Closed by #177

**Closed as completed by david2202** 2016-04-30 03:06 UTC
